create database Lab5;
use Lab5;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

create table `KHACHHANG` (
  `MAKH` varchar(36) NOT NULL,
  `HO` varchar(30),
  `TEN`  varchar(30),
  `NGAYSINH` date,
  `DIACHI` varchar(50),
  `SDT` varchar(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `KHACHHANG`
ADD PRIMARY KEY (`MAKH`);

CREATE TABLE `MONAN` (
   `MAMA` VARCHAR(30) NOT NULL PRIMARY KEY,
   `TENMA` VARCHAR(50),
   `DONGIA` DECIMAL(10,2),
   `LOAIMA` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `HOADON` (
   `MAHD` VARCHAR(30) NOT NULL PRIMARY KEY,
   `MAKH` VARCHAR(36) NOT NULL,
   `THT` DECIMAL(10,2),
   `NGAYHD` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `HOADON`
  ADD CONSTRAINT `FK1` FOREIGN KEY (`MAKH`) REFERENCES `KHACHHANG` (`MAKH`) ON DELETE CASCADE ON UPDATE CASCADE;
  
  
CREATE TABLE `CTHD` (
   `MAHD` VARCHAR(30) NOT NULL,
   `MAMA` VARCHAR(30) NOT NULL,
   `MAK` VARCHAR(50),
   `SL` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
  
ALTER TABLE `CTHD`
  ADD CONSTRAINT `FK2` FOREIGN KEY (`MAHD`) REFERENCES `HOADON` (`MAHD`) ON DELETE CASCADE ON UPDATE CASCADE;
  
ALTER TABLE `CTHD`
  ADD CONSTRAINT `FK3` FOREIGN KEY (`MAMA`) REFERENCES `MONAN` (`MAMA`) ON DELETE CASCADE ON UPDATE CASCADE;
  
ALTER TABLE `CTHD`
  ADD CONSTRAINT `FK5` FOREIGN KEY (`MAK`) REFERENCES `MONAN` (`MAMA`) ON DELETE CASCADE ON UPDATE CASCADE;
  
CREATE TABLE `ACCOUNT`(
	`USERNAME` VARCHAR(50) NOT NULL PRIMARY KEY,
    `MAKH` VARCHAR(36) NOT NULL,
    `PASSWORD` VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
ALTER TABLE `ACCOUNT`
  ADD CONSTRAINT `FK4` FOREIGN KEY (`MAKH`) REFERENCES `KHACHHANG` (`MAKH`) ON DELETE CASCADE ON UPDATE CASCADE;
  
INSERT INTO `KHACHHANG` VALUES ('1', 'NGUYEN', 'KIET', '2003-05-22', '43 TAN LAP, DI AN, BINH DUONG', '0387518892');
  
INSERT INTO `ACCOUNT` VALUES ('USER1', '1', 'ALOALO');
  
COMMIT;
  